### ISSUE TITLE
1) Adding a Mapbox GL JS map to project.

### ISSUE THREAD

**Issue by RicardoBachmann** [RicardoBachmann/visible-borders-detroit#1]
## Value proposition

**As a** user,
**I want to** see a full-screen map centered on Detroit 
**so that** I can start exploring the map immediately.

## Description

<img width="981" alt="Bildschirmfoto 2024-11-14 um 08 24 23" src="https://github.com/user-attachments/assets/99f59f67-c7c6-4e18-97b6-17bd8e2bf39c" width=320px>

## Acceptance criteria: 

- [x] The map should open in full-screen mode for mobile and desktop devices upon loading.
- [x] The map is centered on Detroit with a specific zoom level (e.g., city view).
- [x] There is no other UI element obstructing the initial view of the map.
- [x] The user should be able to zoom in and out and move around the map.

## Complexity

Small

## Tasks

- [x] Create branch `map-component`
- [x] Install Mapbox GL JS library for interactive and customizable maps with `npm install mapbox-gl`
- [x] Create a map container element
- [x] Make sure to assign `mapboxgl.accessToken` compatible with react-vite and store the key in `.env`
- [x] Specify center: as longitude and latitude coordinates in an array ([longitude, latitude]) also zoom level for Detroit
- [x] Install `npm install styled-components` and Add base styles
