### ISSUE TITLE
2) Display of Historical Redlining Districts

### ISSUE THREAD

**Issue by RicardoBachmann** [RicardoBachmann/visible-borders-detroit#4]
## Value proposition

**As a** user,
**I want to** view the historical redlining districts in Detroit displayed on the map
**so that** I can understand which areas were affected by the color-coded practices.

## Description

<img width="970" alt="Bildschirmfoto 2024-11-18 um 12 19 39" src="https://github.com/user-attachments/assets/0614d847-2331-47c8-a680-01d53c910760" width="300px">

<img width="924" alt="Bildschirmfoto 2024-11-18 um 12 52 36" src="https://github.com/user-attachments/assets/ef9b2c67-1491-4890-887c-2a77ca867b0b" width="300px">

## Acceptance criteria: 

- [x] The map should display the historical redlining districts in Detroit as distinct, color-coded areas.
- [x] A legend should be available to explain the meaning of the color codes.
- [x] The user should be able to toggle the redlining layer on and off for better map clarity.
- [x] The redlining layer should be accessible and properly displayed on both mobile and desktop versions of the map.

## Complexity

Medium

## Tasks

1. Setup: 
- [x] Create branch `redlining-component`.
- [x] Import the district data into a GeoJSON file into the project.

2. Rendering Data on the Map:
- [x] Add a GeoJSON layer to the map to display the historical redlining districts.
- [x] Ensure the map view centers on Detroit upon loading the redlining layer.
- [x] Use color coding to represent the different district classifications (e.g., A, B, C, D grades).

3. UI/UX Enhancements:
- [x] Add a legend to explain the color codes and what they represent.
- [x] Implement a toggle switch or button to turn the redlining layer on and off.

4. Responsiveness and Accessibility:
- [x] Ensure the layer and legend are fully responsive and display correctly on mobile and desktop devices.

5. Testing and Validation:
- [x] Test the GeoJSON rendering to ensure districts align accurately with the map.
- [x] Validate the color coding matches the historical data classification.
- [x] Ensure all elements work seamlessly in both mobile and desktop views.

6. Documentation:
- [x] Document the process of adding the GeoJSON layer and its purpose in the README file or developer notes.
